version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_CONN_REDSHIFT=${SCHEME}://${DBUSER}:${PASSWORD}@${HOST}:${PORT}/${SCHEMA}?iam_role=${IAM_ROLE}&region=${REGION}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins/:/usr/local/airflow/plugins
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
